### ISSUE TITLE
poll time

### ISSUE THREAD

**Issue by jorgenbosman** [MislavMandaric/home-assistant-vaillant-vsmart#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would seem that the sensors only update once every hour, which seems a bit too long. In the vsmart app, the temperature history seems to be available for every 10 minutes. Is there a way to make the sensors update every 10 minutes as well?
Sometimes they seem to update more frequently, but I have no clue why...

**Describe alternatives you've considered**
None

**Additional context**
<img width="1140" alt="Screenshot 2021-12-06 204640" src="https://user-images.githubusercontent.com/49554422/144912174-df939468-c132-45a1-9afc-1ad68cb69819.png">
![IMG_3160](https://user-images.githubusercontent.com/49554422/144912602-c2df57bb-e577-42f3-9b01-c2c041427b9d.PNG)

**Comment by MislavMandaric** [comment]
Hey @jorgenbosman.

First of all, thank you for using the integration 👍 

As for the issue you reported, currently configured poll interval is 5 minutes as defined [here](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/blob/master/custom_components/vaillant_vsmart/entity.py#L17).

I won't be able to work on this issue in the next week or two, but in the meantime, please [enable debug logs](https://www.home-assistant.io/integrations/logger/) for `vaillant_vsmart` component and look for the following item in the log:

```
2021-12-03 06:05:21 DEBUG (MainThread) [custom_components.vaillant_vsmart] Finished fetching vaillant_vsmart data in 0.974 seconds (success: True)
```

This log should be written whenever the integration fetches data from the API, which means it should be there every ~5min. If it's not, there is an issue with the updater which I'll try to debug in more details.

**Comment by szmidtpiotr** [comment]
Can it be connected with #21? Looks like problem with updater too

**Comment by jorgenbosman** [comment]
I have enabled debug logging. For now it polls every 5 minutes. We'll see if it stays that way

**Comment by szmidtpiotr** [comment]
Also checked, and can confirm 5 minutes between updater works

**Comment by jorgenbosman** [comment]
Indeed, data is fetched every 5 minutes. However, temperature sensor in hass is only updated every hour. In the vsmart ios app, I can see it change more frequently.

**Comment by MislavMandaric** [comment]
Hey guys. I managed to take some time to take a look at this. I don't understand _why_ it's happening but I might know where to look for more details.

Yes, the component clearly fetches data every 5 minutes.

But for some reason, the entity state in Home Assistant is updated every ~1h if Home Assistant is not being used (eg. during the night), but if you keep using the UI, the state gets properly updated every time. The graph I attached shows this -- marked are the updates when I was fiddling with the UI constantly because I was debugging; before and after the UI was not used and it reverted to ~1h state refresh behavior.

The graph you shared is the history graph which has a data point for each state change in the entity state machine in HA. Some of the things I checked:
* Component fetches data every 5 mins, as can be seen from the log (ie. it's a not a problem with component fetch interval being ignored)
* API returns updated data for those fetch requests (ie. there is no caching on the Vaillant API)
* History graph UI gets all the state data points (ie. it's not that data exists but is not shown in the UI)

The only thing that is left is to find out why is state not updated when new data is fetched from the UI. I'll write an update here on the issue when I find it out.

![image](https://user-images.githubusercontent.com/2945713/147133718-cbf67d95-2f61-471c-a5e8-8a650355366c.png)

**Comment by jorgenbosman** [comment]
Thanks for investigating!

**Comment by MislavMandaric** [comment]
I tried debugging and reproducing this behavior locally and I couldn't find any issues.

I just pushed a new version update which adds one more debug log - whenever new data is fetched from the API, logging the current temperature state value.

Please update to the latest version of the integration in HACS and turn on debug logging. After 24h, please turn off the debug log (to reduce the number of logs the component generates) and share the log here.

Thank you for helping out with this 👍

**Comment by jorgenbosman** [comment]
(Un)fortunately, I am unable to test this, because I got a Tado as Christmas present :-)
Perhaps someone else can continue to test this...

**Comment by Pomezny** [comment]
I'm very interested in this project. Big thanks to @MislavMandaric for excelent work. I will try to provide debug logs within a few days.

**Comment by MislavMandaric** [comment]
Hi everyone.

I managed to test this myself in the last ~week or so and unfortunately, I can't fix this issue.

After adding additional logging, it unfortunately resulted with conclusion that in the end API _does_ cache the current temperature. Response from the API returns the same current temperature value (eg. 22.1) for an ~hour and then returns an updated value (eg. 21.8). I can't figure out why it is not doing the same for the official app, but requests coming from my HA are returning different current temperature values than the official app does, at the same time they are made. In the example I gave, the official app would show both 22.0 and 21.9 in between my start and end value during that hour.

I tried fixing the issue by implementing some well known cache invalidation techniques (adding `Cache-Control` headers and adding a random query parameter to each request) but that didn't help.

I'm going to have to leave it like this for now, because I'm out of ideas and it would take me unreasonable amount of time to get more in depth what does the official app do to get around the cache. Maybe I'll come back to it at some later stage, or if anyone is willing to take this over, that would be great too.

**Comment by Pomezny** [comment]
Interesting discovery. I think that "current state" API call is not returning realtime values, probably caching or some kind of rounding plays a role here. I plan on observing API calls from the oficial app (Tried yesterday with Fiddler, but failed).  I think that there is big probability that caching based on some server side logic and cannot be affected by api calls. Historical data (graph) is probably using different API call to retrieve true values. If thats true, there is no way for us to get identical history data just by logging the "current state". 
I am not familiar with Home assistant integrations yet, but would it be possible to call history API every hour in order to retrieve true values and fill the history graph in HA with them? If the answer is yes, I will dust off my python skills and try to implement it in near future.

**Comment by MislavMandaric** [comment]
> Historical data (graph in app) is probably using different API call to retrieve real/more precise values

You were right with this one, great job 👍 

@superbunika, who previously helped me find other APIs in the app, checked the APIs that are called when accessing the graph and that screen uses a different endpoint, which apparently returns up-to-date values, without caching.

I plan on adding this new API to the library and using it in the component to always have fresh data.

Thanks guys for reporting this and for helping out and thanks to @superbunika for getting the API endpoints used 👍 

> would it be possible to call history API every hour in order to retrieve true values and fill the history graph in HA with them?

Fortunately, this won't be necessary. I'll simply call this new endpoint in the same polling mechanism as the existing one and substitute the cached data with the real time ones for whatever is supported (from what I can see, those are `temperature` and `setpoint_temperature`).

**Comment by MislavMandaric** [comment]
I released a new version right now, which uses the new endpoint for getting real time temperature data.

I upgraded my setup and will report here if things look better than before or not.

Feel free to upgrade yours as well. Lets hope this is it 🤞

**Comment by Pomezny** [comment]
Good job! Got notified and already updated my instance 🤣 I will let you know in a few days how its working on my setup.

**Comment by Pomezny** [comment]
I am running the new version, but most changes in graph still occur in 1 hour interval.
![image](https://user-images.githubusercontent.com/4263174/150672364-ac254d37-6d7c-4454-9f32-775662123b10.png)

**Comment by superbunika** [comment]
Same here.
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6177577/150672825-3be48d74-fff3-4bc0-aeea-71023e70dbf4.png">

**Comment by MislavMandaric** [comment]
Same for me. There are different parameters for the API and I'll try to play around with different values for those parameters.

Unfortunately I still haven't set up some kind of beta release channel to make this testing easier, so I'll probably just publish multiple new versions for it.

Thanks for the feedback, the battle continues 😄

**Comment by Pomezny** [comment]
@MislavMandaric  Publishing new versions is fine with me. I usually update within hours and I can report any changes I notice.

@superbunika how did you inspected API calls from the app? I wasn't successful, with proxy on Android and decompiled sources weren't much help for me. I plan on using my laptop as gateway with traffic forwarding and intercepting all traffic from phone with fiddler but last time I did this on windows it wasn't working that well and messed up my iterfaces for virtual machines which I need for work. So if there is easier solution to inspect and play with API I would appreaciated it.

**Comment by superbunika** [comment]
@Pomezny I was using Postman for proxy, then just specify postman host as proxy inside wifi settings in mobile phone. You also have to generate custom CA cert in Postman and import it in your mobile phone as Postman generates needed certs on the fly for HTTPS. Accidently stumbled on it and it's great for reverese engineering APIs.

What I would like is to be able to insert custom CA cert in Vaillant/MiGo gateway and then we could reverse engineer Netatmo API and host it locally for a true cloudless solution, but that's another story.. :)

**Comment by Pomezny** [comment]
@superbunika fiddler is very similiar in this regard (proxy, custom CA, efectivelly MITM attack on the phone). But app ignores proxy settings on phone. AFAIK on Android apps don't have to use proxy which made this useless for me. App can set this in manifest IIRC from Android 6. Thinking about this it might be more feasible to get my hands on iPhone and use that, since in iOS all apps use proxy set by user.

**Comment by MislavMandaric** [comment]
Hey, I'm trying out different options for the new APIs and I can't make it work.

The `getmeasure` API always returns the same latest value as `getthermostatdata` API for me. I tried various options and result is always the same.

In the meantime, the official Vaillant eRELAX/vSMART got updated and it seems to me that in the new version, graph screen from the screenshot posted by @jorgenbosman also has "wrong" out-of-date data.

Looking at my app currently, indoor temperature on the main screen is set to 22.2, but the graph screen shows out-of-date 21.9 as the latest value. There is either _another_ API or we're back to square one on this issue.

**Comment by Pomezny** [comment]
@MislavMandaric 
I have MiGo from Protherm, controlling furnace Protherm Tiger 20/26 KKZ21-CS/1.  Both "MiGo. Your Heating Assistant" and "Vaillant vSMART Control" were updated on April 29, with identical changelog. I remember the "big update", which reworked UI and added current pressure in heating system to settings, but I dont think it was this last one. Graph is working in my app. To be honest I did not spent much time looking at it last few weeks but I just checked and it seems to work as expected. (ie working as before: graph being more precise, current temperature being rounded/delayed).

Attached video:
https://user-images.githubusercontent.com/4263174/174900340-5c7ac597-bd1e-46df-ad58-cf2f3844409d.mp4

**Comment by superbunika** [comment]
@MislavMandaric I have nearly identical setup as @Pomezny and in-app graph seems to work fine. At one point it was not showing correct data but it was solved with a minor update (about a month ago cca).

**Comment by rydercowan** [comment]
Following integration update yesterday current temperature from vSMART is not updating in HA. Reloading integration successfully forces temperature update.

**Comment by superbunika** [comment]
My observation regarding this is the following and started hapenning I think around the time the app was updated with the new UI:
1. The room temperature on thermostat card does not update at all unless I open the Vaillant/Migo mobile app. Then HA pulls that new value and displays it until I push a new value by opening the mobile app again.
2. This is how it looks on my end. Today at about 2:10PM I've opened the mobile app and then the temperature in HA updated.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/6177577/179565057-73c2d4fd-c627-4415-8554-f14d17a32521.png">

I guess they changed the API endpoints a little bit.

**Comment by rydercowan** [comment]
Opening the Vaillant app doesn't cause room temperature  to update in HA for me. Reloading the integration appears the only way to force it to update.

**Comment by Fzabik** [comment]
Is there any progress on the Vaillant VSmart refresh bug ?
Temperature and mode are updated when I open Vaillant application Or When I restart HA.
Automations with service "setHvacMode" seems working properly.
How can we help you to track and correct this bug ?

**Comment by MislavMandaric** [comment]
Unfortunately, no. 😞 

I'm using both APIs (ie. getting thermostat data and getting precise temperature measurements) and both APIs return the same values, those that look like cached compared to the official app.

I managed to get the data in the official app work properly, so I'm back to square one - official app looks good, but using the same APIs from the integration returns stale readings.

**Comment by janchlebek** [comment]
I think I have another one related to this: when I turn on/off the switch.thermostat_hwb it does trigger the on/off action to the Vaillant API but the switch state does not update (leaving the switch status inconsistent with the status of the boiler) until I call the service again or toggle the switch again. Reloading the integration fixes the incorrect state.

**Comment by compunix-be** [comment]
> I think I have another one related to this: when I turn on/off the switch.thermostat_hwb it does trigger the on/off action to the Vaillant API immediately (mode is changed in app on my phone within 2 seconds) but the switch state does not update (leaving the switch status inconsistent with the status of the boiler) until I call the service again or toggle the switch again. Reloading the integration also fixes the incorrect state of the switch so it matches the API.

I can confirm this related issue. I noticed it when creating an automation, didn't investigated in depth, but used a similar workaround by calling the service again a second time a few seconds later.

**Comment by kimbo1st** [comment]
What I also notice is that when I change a setting, it is not directly reflected in the HA. So when I by example put the heating up, the status doesn't change and it takes some time to do. So I need to double check in the Vaillant app itself to be sure it has taken it. So don't know if possible that when you do changes in HA, it reads after a few seconds also the status on the Vaillant and set it correctly in HA.

**Comment by MislavMandaric** [comment]
I think this is the same issue that was reported in #21. Both of them _could_ have the same root cause, but I'm not so sure anymore.

In this one, the problem is that I get "wrong" (ie. cached) value for current temperature, even after I manually invoke the API.

But in the other one it seems as that, after something is changed in HA, the API is not invoked again quickly enough, but when it is called, proper values are returned immediately. So the problem might be solved by calling the API again manually.

**Comment by kimbo1st** [comment]
For me the same behavior.. it updates the temp as soon I open the Vaillant app on my mobile phone.

**Comment by MislavMandaric** [comment]
Hey everyone.

I just published a new version v0.6.1. I _think_ this might have solved the problem (#198). If you want to test it out, please update to that version (or higher) and if you have some time, report back here if the behavior is as expected or it's still not working properly.

I'm also trying to set up prereleases so in the future some updates like these will probably go to `beta` first. If you see `beta` version available and want to help out with testing, feel free to use it.

**Comment by Pomezny** [comment]
It looks very promising. Gathered only ~2 hours of data, you can see spike in temperature when I was messing with it after update. Graph after update is way denser than before. I will try to keep an eye on the graphs for a few days.

![image](https://user-images.githubusercontent.com/4263174/200141838-d17e125e-0562-4250-8461-cfb74e8e111c.png)

**Comment by superbunika** [comment]
Looking good after the update!
![image](https://user-images.githubusercontent.com/6177577/200163826-3514d391-f9c5-42e3-bd78-340951bd79ff.png)

**Comment by rydercowan** [comment]
Now appears to be working correctly here - well done.

**Comment by MislavMandaric** [comment]
Awesome! I'm so glad this is finally resolved 😀 Thanks everyone for helping out with it and for the patience while waiting for the fix, I really appreciate it!

**Comment by kimbo1st** [comment]
Is the refresh time 5 minutes? Because when the heating turns on I don't see it changing right away.

Met vriendelijke groet,

Kim Verheyden
________________________________

**Comment by MislavMandaric** [comment]
Yes, refresh time is 5min.

Let's keep track of that issue in #21, as I believe that's separate from this one after all.
