### ISSUE TITLE
error when only hot water planning active

### ISSUE THREAD

**Issue by compunix-be** [MislavMandaric/home-assistant-vaillant-vsmart#79]
## Version of the custom_component
version 0.4.0
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Custom component has been working without error when in heating mode (with setpoint for temperature).
Beginning this week, I've changed to water heating only (or summer mode) and error started to appear in home-assistant.log of exception not been handled.
As an additional effect, 'climate.thermostaat' is now unavailable.

## Debug log

2022-03-13 09:44:48 DEBUG (MainThread) [custom_components.vaillant_vsmart] _temperature_: 20.6
2022-03-13 09:44:48 DEBUG (MainThread) [custom_components.vaillant_vsmart] setpoint_temp: None
2022-03-13 09:44:48 DEBUG (MainThread) [custom_components.vaillant_vsmart] _temperature_: 20.6
2022-03-13 09:44:48 DEBUG (MainThread) [custom_components.vaillant_vsmart] setpoint_temp: None
2022-03-13 09:44:48 DEBUG (MainThread) [custom_components.vaillant_vsmart] Finished fetching vaillant_vsmart data in 1.701 seconds (success: True)
2022-03-13 09:44:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
    if self.hvac_action:
  File "/config/custom_components/vaillant_vsmart/climate.py", line 126, in hvac_action
    if self._module.measured.temperature < self._module.measured.setpoint_temp:
TypeError: '<' not supported between instances of 'float' and 'NoneType'

```text

Add your logs here.


![Screenshot from 2022-03-13 10-09-21](https://user-images.githubusercontent.com/98172746/158052789-4841e20a-96c7-4a28-89df-012ed7cfbcf1.png)

```

**Comment by MislavMandaric** [comment]
Thank you for reporting this issue, and for providing a detailed log with it 👍 

I see where the problem is and will try to fix it immediately. I'll write here once the fix is available through HACS.

**Comment by MislavMandaric** [comment]
The fix is available through HACS.

**Comment by compunix-be** [comment]
Thanks for having a look at this.
I've done the upgrade to 0.4.1, but there is still an issue according the logs:
2022-04-09 08:54:05 DEBUG (MainThread) [custom_components.vaillant_vsmart] setpoint_temp: None
2022-04-09 08:54:05 DEBUG (MainThread) [custom_components.vaillant_vsmart] _temperature_: 18.6
2022-04-09 08:54:05 DEBUG (MainThread) [custom_components.vaillant_vsmart] setpoint_temp: None
2022-04-09 08:54:05 DEBUG (MainThread) [custom_components.vaillant_vsmart] Finished fetching vaillant_vsmart data in 0.469 seconds (success: True)
2022-04-09 08:54:05 ERROR (MainThread) [custom_components.vaillant_vsmart.climate] '<' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/climate.py", line 127, in hvac_action
    if self._module.measured.temperature < self._module.measured.setpoint_temp:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2022-04-09 08:54:05 ERROR (MainThread) [custom_components.vaillant_vsmart.climate] '<' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/climate.py", line 127, in hvac_action
    if self._module.measured.temperature < self._module.measured.setpoint_temp:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
